export const ACTION_TYPES = {
    // Auth
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    PASSWORD_CHANGE: "PASSWORD_CHANGE",

    // Products
    PRODUCT_CREATE: "PRODUCT_CREATE",
    PRODUCT_UPDATE: "PRODUCT_UPDATE",
    PRODUCT_DELETE: "PRODUCT_DELETE",

    // Inquiries
    INQUIRY_CREATE: "INQUIRY_CREATE",
    INQUIRY_STATUS_UPDATE: "INQUIRY_STATUS_UPDATE",
    INQUIRY_ASSIGN: "INQUIRY_ASSIGN",

    // Agents
    AGENT_CONFIG_UPDATE: "AGENT_CONFIG_UPDATE",
    AGENT_RUN: "AGENT_RUN",
    AGENT_ERROR: "AGENT_ERROR",
    AGENT_CREATE: "AGENT_CREATE",

    // UI Content
    UI_HEADER_UPDATE: "UI_HEADER_UPDATE",
    UI_SLIDER_UPDATE: "UI_SLIDER_UPDATE",
    UI_FOOTER_UPDATE: "UI_FOOTER_UPDATE",
    UI_PROMO_UPDATE: "UI_PROMO_UPDATE",

    // Settings
    SETTINGS_UPDATE: "SETTINGS_UPDATE",
    API_LIMIT_UPDATE: "API_LIMIT_UPDATE",
    EMPLOYEE_ROLE_UPDATE: "EMPLOYEE_ROLE_UPDATE",
};
